### ISSUE TITLE
Consider swapping the arguments of the write functions

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#16]
Hello!

Hayleigh mentioned that she tends to get the order of the arguments of the file write functions wrong, giving the path first then the contents. I also pretty consistently get this wrong, so I checked other languages and made some polls:

- https://twitter.com/louispilfold/status/1723433161558822997
- https://hachyderm.io/deck/@lpil/111393731831145371

It seems that the other order is by far more common. Do you think it'd be worth switching over to that?

Cheers,
Louis

**Comment by bcpeinhardt** [comment]
Yeah that's fair haha. It's set up that way with pipes in mind.

`data |> write(to: filename)`

But I suppose swapping them wouldn't be too disruptive to that.

`data |> write(to: filename, _)`

I would be open to switching the pattern around, will give it a good think.

**Comment by lpil** [comment]
My preferences would be in this order, from favourite to least favourite:

1. Change argument order
2. Keep the same
3. Builder 
4. New name

I think this because I believe a library like this is about being predictable and easy to use, and people have fairly strong opinions about what a file system API looks like. Making something unusual ought to have a strong motivator to make it worth that strangeness cost.

That new name is last as I don't think it actually solves the problem, which is evidenced by the problem already existing for the `write_bits` function.

```gleam
write_data(filename, path)
write_data(path, filename)
```

**Comment by bcpeinhardt** [comment]
Yeah after playing with it I agree. Will change the order and do a version bump and publish this evening when I'm done with work :)

**Comment by bcpeinhardt** [comment]
Published :)
