### ISSUE TITLE
Files to set permissions

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#17]
Hello!

I'd like to be able to change the permissions of files, namely I want to make a file executable. Could this library do this?

Thanks,
Louis

**Comment by bcpeinhardt** [comment]
Yeah that seems super reasonable. I'll take a look when I have the chance!

**Comment by bcpeinhardt** [comment]
v1.1.0 has `set_permissions` and `set_permissions_octal` :)
