### ISSUE TITLE
Bug: `get_files` returns filepaths with duplicate slashes when the directory name has a trailing slash

### ISSUE THREAD

**Issue by TanklesXL** [bcpeinhardt/simplifile#18]
given the call `simplifile.get_files("./static/posts/")` and `static/posts` having the file `test_post.md`, the returned path is falsely `"./static/posts//test_post.md"`

**Comment by bcpeinhardt** [comment]
Fixed :) just upgrade v1.1.0 -> v1.1.1 :)
