### ISSUE TITLE
Current working directory function

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#19]
Hello!

It would be super useful to be able to get the current working directory. Would this be something this library could do?

Thanks,
Louis

**Comment by bcpeinhardt** [comment]
Yeah I think that's a great idea, will add it tonight when I get the chance 😌

**Comment by bcpeinhardt** [comment]
The new function is called `current_directory` :)

**Comment by lpil** [comment]
Thank you!
