### ISSUE TITLE
Function for reading entries of a directory

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#2]
Hello! Could we get a function for reading the contents of a directory? It would be very handy!

**Comment by bcpeinhardt** [comment]
Can you clarify? Looking for an iterator over the files in a directory or something lower level?

**Comment by bcpeinhardt** [comment]
Lol I just saw the issue title xD yeah that's a great idea I can work on that :)

**Comment by bcpeinhardt** [comment]
This is published so I'm going to close this issue :)

**Comment by lpil** [comment]
Thank you!!
