### ISSUE TITLE
create_directory_all no longer works after v1.16

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#26]
Hello!

I'm not sure what the issue is but the tests that use it in Wisp have broken since upgrading to v1.16.

For example, if I attempt to create the directory `/tmp/gleam-wisp/akjsPO4_D67WynKA` it returns OK but no directory is created.

Thanks,
Louis

**Comment by bcpeinhardt** [comment]
Ruh roh, looking into it! If i'm doin stuff in the discord and you think I haven't seen an issue feel free to ping me there too :) 
I'm assuming that was meant to be version 1.6, what was the previous version?

**Comment by bcpeinhardt** [comment]
Oh I see I introduced the bug should be fixed in a tick

**Comment by bcpeinhardt** [comment]
v1.6.1 published, need to find a good way to test absolute paths in CI and/or mark certain tests not to run in CI.
Well, I guess I need a way to run test suites. I can do that, could be a good reason to work on test framework stuff.

**Comment by lpil** [comment]
Thank you!
