### ISSUE TITLE
[Request] Read file chunks

### ISSUE THREAD

**Issue by ALX99** [bcpeinhardt/simplifile#29]
If I have not misunderstood things, currently it is only possible to read files as a whole, which makes it impossible to use this library for large files

I would like to request a feature that allows you to read the file in chunks (read `x` bytes at a time for example).

**Comment by bcpeinhardt** [comment]
@ALX99 did you check out the file streams library linked it the README? I think that's probably what you're after.

**Comment by ALX99** [comment]
Ahh, sorry I missed it!
Thank you for the help 🙇
