### ISSUE TITLE
Expose `lstat` / `read_link_info`

### ISSUE THREAD

**Issue by joshi-monster** [bcpeinhardt/simplifile#34]
Hi!

currently there is no way to get the stat object for a symbolic link, outside of knowning that something is a symlink by using `is_symlink`.

Hayleigh suggested that I use simplifile for my file watcher library, but unfortunately,  I would also need to have access to the last modified timestamp / other stat data for the symlink itself, not just the target it points to.

Would this be something you'd consider adding?
Thanks, ~yoshi

**Comment by bcpeinhardt** [comment]
Hmmm. The `file_info` function returns a `FileInfo` object which includes the last modified time (mtime_seconds since the unix epoch iirc).
What other info were you looking for? We do a custom object because different info is available in different shapes on node vs deno vs bun vs erlang.
