### ISSUE TITLE
Add function: create_file_all

### ISSUE THREAD

**Issue by TanklesXL** [bcpeinhardt/simplifile#42]
Similar to [`create_directory_all`](https://hexdocs.pm/simplifile/simplifile.html#create_directory_all), would you be open to adding a function that works for creating a file at the specified path, creating the necessary directories recursively along the way?

**Comment by bcpeinhardt** [comment]
Hmmm. I don't think so. My concerns:

1. People will use it for files in the same directory, especially in a loop, which would lead to a lot of unnecessary work checking the directory structure exists each time.
2. What should it do if the file exists? It feels confusing for the function to fail if the file exists but not fail if the directories exist, but I don't think overwriting would be anyone's desired behavior either.

What's your use case? Maybe it's worth having and documenting the footguns.

**Comment by bcpeinhardt** [comment]
I don't know of any stdlib file modules in other languages that have this, I wonder what their reasoning was.

**Comment by TanklesXL** [comment]
Hmmm yeah you're not wrong, my use case is for gladvent where I create a bunch of files in the same subdirectory. I wanted to create the file without first checking if I need to create the dir every single time. but I agree it does seem awkward now that you've laid it out. 

Maybe I need to rethink my approach
