### ISSUE TITLE
Recursively make directory

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#6]
Hello!

It would be handy to have a function which will create a directory and any parent directories that need to be created.

Cheers,
Louis

**Comment by bcpeinhardt** [comment]
This function exists now and is called `create_dir_all`.

**Comment by lpil** [comment]
Thank you

**Comment by bcpeinhardt** [comment]
Yeah I have some docs updates to make too, I think I'm gonna make this change.

**Comment by lpil** [comment]
Personally I would probably go for `directory` as core libraries don't use abbreviations anywhere, for clarity, but both seem fine.

**Comment by bcpeinhardt** [comment]
This is done now :)
