### ISSUE TITLE
FFI module using a name unrelated to this module

### ISSUE THREAD

**Issue by lpil** [bcpeinhardt/simplifile#9]
Hello!

The Erlang FFI module is called `gleam_erlang_ffi` rather than `simplifile_ffi` or similar, so it will likely clash with the `gleam_erlang` library, resulting in cryptic errors and mysterious bugs.

Best rename it to be part of this package and unlikely to clash.

Cheers,
Louis

**Comment by bcpeinhardt** [comment]
The modules are now `simplifile_erl` and `simplifile_js`

**Comment by lpil** [comment]
Thank you!
